return {
	---- Weapons Category ----

	iron_sword = { name = "Iron Sword", subCategory = "Sword" },
	wooden_sword = { name = "Wooden Sword", subCategory = "Sword" },
	steel_sword = { name = "Steel Sword", subCategory = "Sword" },
	iron_knife = { name = "Iron Knife", subCategory = "Knife" },
	rusty_knife = { name = "Rusty Knife", subCategory = "Knife" },
	long_bow = { name = "Long Bow", subCategory = "longBow" },
	short_bow = { name = "Short Bow", subCategory = "shortBow" },

	---- Armors Category ----

	iron_chestplate = { name = "Iron Chestplate", subCategory = "Heavy" },
	iron_leggings = { name = "Iron Leggings", subCategory = "Heavy" },
	iron_boots = { name = "Iron Boots", subCategory = "Heavy" },
	iron_helmet = { name = "Iron Helmet", subCategory = "Heavy" },
	leather_vest = { name = "Leather Vest", subCategory = "Light" },
	leather_leggings = { name = "Leather Leggings", subCategory = "Light" },
	leather_boots = { name = "Leather Boots", subCategory = "Light" },
	leather_cap = { name = "Leather Cap", subCategory = "Light" },

	---- Crafting Ingredients ----

	bone_fragment = {
		name = "Bone Fragment",
		subCategory = "Material",
		description = "Bones collected from skeletons. Their properties are best for light weapons and armors.",
	},
	torn_cloth = {
		name = "Torn Cloth",
		subCategory = "Material",
		description = "Scraps of leather collected from monsters. Used to make armor.",
	},
	iron_shard = {
		name = "Iron Shard",
		subCategory = "Material",
		description = "Small pieces of iron which is usefull for making various armors and weapons.",
	},

	---- Rarity Colors ----

	rarity = {
		common = Color3.fromHex("#c4cfc8"),
		uncommon = Color3.fromHex("#86a7ac"),
		rare = Color3.fromHex("#4b7cb7"),
		epic = Color3.fromHex("#7255a1"),
		legendary = Color3.fromHex("#ffb155"),
		mythic = Color3.fromHex("#b86440"),
		secret = Color3.fromHex("#302033"),
		secretText = Color3.fromHex("#b83a2d"),
	},
}
