return {
	boneSet = {
		pieces = { "bone_helmet", "bone_chestplate", "bone_leggings", "bone_boots" },
		bonus = { armor = 10 },
	},
	leatherSet = {
		pieces = { "leather_helmet", "leather_chestplate", "leather_leggings", "leather_boots" },
		bonus = { armor = 15 },
	},
	ironSet = {
		pieces = { "iron_helmet", "iron_chestplate", "iron_leggings", "iron_boots" },
		bonus = { armor = 20 },
	},
	steelSet = {
		pieces = { "steel_helmet", "steel_chestplate", "steel_leggings", "steel_boots" },
		bonus = { armor = 25 },
	},
}
