return {
	setName = "boneSet",
	setBonus = { armor = 20, passives = "none" },
	pieces = {
		helmet = { id = "bone_helmet", baseArmor = 8, baseHealth = 10, baseLuck = 0 },
		chestplate = { id = "bone_chestplate", baseArmor = 14, baseHealth = 15, baseLuck = 0, baseCritRate = 0 },
		leggings = { id = "bone_leggings", baseArmor = 10, baseHealth = 12, baseLuck = 0, baseCritRate = 0 },
		boots = { id = "bone_boots", baseArmor = 6, baseHealth = 8, baseLuck = 0, baseSpeed = 0 },
	},
}
