return {
	setName = "steelSet",
	setBonus = { armor = 25, passives = "none" },
	pieces = {
		helmet = { id = "steel_helmet", baseArmor = 10, baseHealth = 12, baseLuck = 0 },
		chestplate = { id = "steel_chestplate", baseArmor = 13, baseHealth = 18, baseLuck = 0, baseCritRate = 0.02 },
		leggings = { id = "steel_leggings", baseArmor = 10, baseHealth = 15, baseLuck = 0, baseCritRate = 0 },
		boots = { id = "steel_boots", baseArmor = 6, baseHealth = 8, baseLuck = 0, baseSpeed = 0 },
	},
}
