return {
	setName = "ironSet",
	setBonus = { armor = 20, passives = "none" },
	rarity = "common",
	pieces = {
		helmet = { id = "iron_helmet", baseArmor = 8, baseHealth = 10, baseLuck = 0 },
		chestplate = { id = "iron_chestplate", baseArmor = 14, baseHealth = 15, baseLuck = 0, baseCritRate = 0 },
		leggings = { id = "iron_leggings", baseArmor = 10, baseHealth = 12, baseLuck = 0, baseCritRate = 0 },
		boots = { id = "iron_boots", baseArmor = 6, baseHealth = 8, baseLuck = 0, baseSpeed = 0 },
	},
}
