return {
	setName = "leatherSet",
	setBonus = { armor = 15, passives = "none" },
	rarity = "common",
	pieces = {
		helmet = { id = "leather_cap", baseArmor = 5, baseHealth = 8, baseLuck = 0 },
		chestplate = { id = "leather_vest", baseArmor = 12, baseHealth = 12, baseLuck = 0, baseCritRate = 0 },
		leggings = { id = "leather_leggings", baseArmor = 8, baseHealth = 10, baseLuck = 0, baseCritRate = 0 },
		boots = { id = "leather_boots", baseArmor = 4, baseHealth = 6, baseLuck = 0, baseSpeed = 0 },
	},
}
